### ISSUE TITLE
Dynaslack wrapped in Custom node deletes all wires

### ISSUE THREAD

**Issue by josols** [radumg/DynaSlack#11]
## Actual Behavior

If I wrap up a DynaSlack workflow in a Custom node, on run all my wires disappear and the Slack-URL also disappears from the custom node.

![dynaslack](https://user-images.githubusercontent.com/7080648/36367880-fb4bea16-1554-11e8-97c3-13c58678598b.gif)

If test files are needed drop me an email, since I don't wanna share the Slack-links to alle parties.. :)

## Specifications

    - Dynamo :  1.3.1
    - Revit 2018.1
    - Operating system :  Windows 7

**Comment by radumg** [comment]
Hey @josols , thanks for filing the bug, looks very strange indeed!
Please forward the test files via email and i'll have a look.

Meanwhile, could you confirm if this happens  :
- only on your machine
- in Revit 2017 too ?
- where is the custom node & all packages saved ? Might be a permissions issue with networkw-hosted DLLs, etc.

**Comment by josols** [comment]
I'm terrribly sorry for the late reply.. As it turns out, this isn't Dynaslacks fault. We included some other custom packages that created this error (Designtechs Dynamo query nodes). Once these were pulled out of the custom node everything works as expected. Closing this issue.

**Comment by radumg** [comment]
Thanks @josols for the update - it makes sense, I know @MarkThorley 's nodes do some funky (unsupported) stuff to get access to Dynamo's API :stuck_out_tongue:
